### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [quartata/rotor-lang#2]
What is your license for this? This would be under copyright by default and is, but with added permissions granted by the [Github Terms of Service](https://help.github.com/articles/github-terms-of-service/).

**Comment by phase** [comment]
_prays for MIT_

**Comment by ghost** [comment]
Yeah, I just want FOSS. If this is proprietary...

**Comment by phase** [comment]
He was talking about licensing it under LGPL

**Comment by quartata** [comment]
Sorry for not adding a license. It is now GPL.

**Comment by quartata** [comment]
Oops, I have just accidentally overwritten some changes (local copy was out of date). One second.

**Comment by phase** [comment]
oh no never force push

**Comment by quartata** [comment]
I believe I have fixed all the issues. Sorry for the confusion.
